invalid pre-processor command
unexpected end of file
file not found $
invalid lexical token
invalid macro usage
line buffer overflow
file stack full
invalid conversion
undefined identifier $
invalid subscript expression
string too large or not terminated
invalid structure reference
member name missing
undefined member $
invalid function call
invalid function argument
too many operands
unresolved operator
unbalanced parentheses
invalid constant expression
illegal use of aggregate
structure used as function argument
invalid use of conditional operator
pointer operand required
lvalue required
arithmetic operand required
arithmetic or pointer operand required
missing operand
invalid pointer operation
pointers do not point to same object
integral operand required
invalid conversion specified
illegal initializer expression
invalid initializer expression
closing brace expected
statement not preceded by case/default
duplicate statement label $
unbalanced braces
invalid use of keyword
break not inside loop or switch
case not inside switch
invalid case expression
duplicate case value
continue not inside loop
default not inside switch
more than one default
while missing from do statement
invalid while expression
else not associated with if
label missing from goto
label name conflict $
invalid if expression
invalid return expression
invalid switch expression
no case values for switch statement
colon expected
semi-colon expected
missing parenthesis
invalid storage class
incompatible aggregate types
undefined structure tag $
structure/union type mismatch
duplicate declaration of item $
structure contains no members
invalid function definition
invalid array limit expression
illegal object
illegal object for structure
structure includes instance of self
illegal object for formal
formal declaration error $
external item attribute mismatch
declaration expected
initializer data truncated
invalid sizeof expression
left brace expected
identifier expected
undefined statement label $
duplicate enumeration value
invalid bit field
pre-processor symbol loop
maximum object/storage size exceeded
reference beyond object size
redefinition of pre-processor symbol $
function return value mismatch
formal definitions conflict with type list
argument count incorrect
argument type incorrect
constant converted to required type
invalid argument type specifier
illegal void operand
statement has no effect
no reference to identifier $
uninitialized auto variable $
attempt to write to const section
