/*
 *  env.h       Environment string operations
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2023 The Open Watcom Contributors. All Rights Reserved.
 * Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */
#ifndef _ENV_H_INCLUDED
#define _ENV_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

#ifndef __COMDEF_H_INCLUDED
 #include <_comdef.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

/*
 *  ISO C types
 */
#ifndef __cplusplus
 #ifndef _WCHAR_T_DEFINED
 #define _WCHAR_T_DEFINED
  #define _WCHAR_T_DEFINED_
  typedef unsigned short wchar_t;
 #endif
#endif

/*
 *  ISO C Prototypes.
 */
#ifdef __cplusplus
namespace std {
#endif
_WCRTLINK extern char       *getenv( const char *__name );
#ifdef __cplusplus
} // namespace std
using std::getenv;
#endif

/*
 *  POSIX 1003.1 Prototypes.
 */
#if defined( _POSIX_SOURCE ) || !defined( _NO_EXT_KEYS ) /* extensions enabled */
_WCRTLINK extern int        putenv( const char *__string );
_WCRTLINK extern int        setenv( const char *__name, const char *__newvalue, int __overwrite );
_WCRTLINK extern int        unsetenv( const char *__name );
#endif /* extensions enabled */

/*
 *  Open Watcom extension
 */
#if !defined( _NO_EXT_KEYS ) /* extensions enabled */
_WCRTLINK extern int        clearenv( void );
_WCRTLINK extern int        _putenv( const char *__string );
_WCRTLINK extern wchar_t    *_wgetenv( const wchar_t *__name );
_WCRTLINK extern int        _wputenv( const wchar_t *__env_string );
_WCRTLINK extern int        _wsetenv( const wchar_t *__name, const wchar_t *__newvalue, int __overwrite );
_WCRTLINK extern int        _wunsetenv( const wchar_t *__name );
#endif /* extensions enabled */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
