///////////////////////////////////////////////////////////////////////////
// FILE: new/new.h (Dynamic memory support)
//
// =========================================================================
//
//                          Open Watcom Project
//
// Copyright (c) 2004-2023 The Open Watcom Contributors. All Rights Reserved.
// Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
//
//    This file is automatically generated. Do not edit directly.
//
// =========================================================================
//
// Description: This header is part of the C++ standard library.
///////////////////////////////////////////////////////////////////////////
#ifndef _NEW_H_INCLUDED
#define _NEW_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

#ifndef _NEW_INCLUDED
 #include <new>
#endif
using std::new_handler;
using std::set_new_handler;

#endif
