///////////////////////////////////////////////////////////////////////////
// FILE: strstream/strstream.h (strstream support)
//
// =========================================================================
//
//                          Open Watcom Project
//
// Copyright (c) 2004-2023 The Open Watcom Contributors. All Rights Reserved.
// Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
//
//    This file is automatically generated. Do not edit directly.
//
// =========================================================================
//
// Description: This header is part of the C++ standard library. It
//              defines the necessary classes for strstream support.
///////////////////////////////////////////////////////////////////////////
#ifndef _STRSTREAM_H_INCLUDED
#define _STRSTREAM_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

#ifndef _STRSTREAM_INCLUDED
 #include <strstream>
#endif
using std::strstreambuf;
using std::strstreambase;
using std::istrstream;
using std::ostrstream;
using std::strstream;

// All included names should also be in the global namespace.
#ifndef _IOSTREAM_H_INCLUDED
 #include <iostream.h>
#endif

#endif
